-- ─────────────────────────────────────────────────────────────────────────
-- BACKUPS BUCKET — private storage for scheduled weekly DB backups
-- ─────────────────────────────────────────────────────────────────────────
-- Used by /api/cron/weekly-backup. Each run uploads a JSON dump named
-- backup-YYYY-MM-DD.json and prunes files older than ~12 weeks.
--
-- Bucket is PRIVATE — access only via signed URL generated by the cron
-- (sent in the weekly admin email) or by admin auth from /admin.
-- ─────────────────────────────────────────────────────────────────────────

insert into storage.buckets (id, name, public)
values ('backups', 'backups', false)
on conflict (id) do nothing;

-- RLS: only admin (via service role from server-side cron + admin reads) can
-- access. Storage default policies already block public access since
-- bucket is private; we add explicit admin-read for clarity.

drop policy if exists "admin read backups" on storage.objects;
create policy "admin read backups"
  on storage.objects for select
  using (
    bucket_id = 'backups'
    and exists (
      select 1 from public.user_roles
      where user_id = auth.uid() and role = 'admin' and is_active = true
    )
  );

-- Service role bypasses RLS entirely, so the cron upload always works.
