-- supabase/kb_from_help.sql
-- Generated by scripts/generate-kb-from-help.js from app/admin/help/HelpClient.tsx
-- Run in Supabase SQL Editor. Re-runnable: ON CONFLICT (slug) DO UPDATE.
-- Every text field uses dollar-quoting so markdown content can contain
-- any character without escaping concerns.

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-intro$kbf$, $kbf$Welcome — what this platform does$kbf$, $kbf$This is your complete rental management system. It handles bookings,
payments, customers, inventory, dispatch, drivers, damages —
everything end-to-end.

The platform is split into **4 sections**:

- **/admin** — you (admin) and your staff manage the business

- **/portal** — customers log in to see their bookings + earn points

- **/driver** — your crew sees today's routes on their phone

- **/** (public) — where customers book online

⏱ **Time to first booking:** Setup takes ~1 hour if you bulk-upload
your products/inventory. After that, customers can book online + pay 24/7.$kbf$, $kbf$Setup$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-products$kbf$, $kbf$Step 1 — Add your rental products$kbf$, $kbf$Products are what customers rent: bounce houses, slides, accessories.

Option A: One by one

- Go to `Products` → click **+ Add product**

- Fill name, slug (auto), category, price/day, cost (internal), stock, image URL

- Optional: weekend rate, setup area, age group

- Save

Option B: Bulk via CSV (faster for 5+ products)

- Go to `Products` → click **Bulk upload**

- Click **Download CSV template**

- Open in Excel/Google Sheets, fill rows, save as `.csv`

- Upload + import. Errors show inline per row.

💡 **Pro tip:** Use bulk upload for the initial 14-product seed,
then edit individuals as needed.

CSV columns:

- `name`, `slug` (optional — auto from name), `category`, `description`

- `price_per_day_dollars`, `cost_dollars`, `stock`, `image_url`

- `is_active` (true/false), `is_addon` (true/false), **`tax_exempt`** (true/false — new!)

- `weekend_price_per_day_dollars`, `setup_area`, `actual_size`, `outlets_required`, `age_group`

✓ Set `tax_exempt=true` on rows where the product shouldn't be taxed (gift cards, fees, non-taxable services). Revenue still counts toward booking totals; just no tax on that row.$kbf$, $kbf$Catalog$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-inventory$kbf$, $kbf$Step 2 — Track operational gear (inventory)$kbf$, $kbf$**Inventory ≠ Products.** Inventory is operational gear (generators,
blowers, anchors, sandbags, cleaning supplies). Products are what
customers rent. Inventory is what you bring to make the rental work.

Why track inventory:

- Driver checklist: "Truck 1 needs 4 blowers + 12 sandbags"

- Maintenance log per item (repair history, ROI)

- Damage tracking

Setup:

- Go to `Inventory` → use Bulk upload or Add item

- For each Product, go to `Products → Edit → Inventory checklist`

- Add what the product needs (e.g. Game On = 1 blower + 6 stakes if grass)

- Use "Copy from another product" to clone settings between similar bouncys$kbf$, $kbf$Catalog$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-important-tips$kbf$, $kbf$Important tips & policies — shows up in 4 places$kbf$, $kbf$One block of customer-facing policies (payment methods, surface
restrictions, staking, weather/cancellation, park requirements,
setup time) is now editable in one place and surfaced everywhere
customers might need to see it.

Edit once at:

-
`/admin/site` → scroll to **Important tips**
(textarea). Edit freely — use blank lines between paragraphs.

Shows up in:

-
**Booking confirmation email** — appended in a
yellow accent box at the bottom of the email body.

-
**Quote email** (when you click Send to customer)
— same yellow accent box, so the customer reads the policies
before they approve.

-
**Public page**
`/info/policies` — full-page version with the
tenant's phone + email at the bottom. Link from anywhere.

-
**FAQs** at `/info/faqs` — each tip
auto-seeded as its own FAQ entry. Customers searching common
questions find the answers in their native format.

⚠️ This is OPERATIONAL policy, not legal. The liability waiver
at `/admin/waiver` is separate — keep it focused on
legal language (assumption of risk, indemnification) and put
day-to-day reminders here.$kbf$, $kbf$Policies$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-tax$kbf$, $kbf$Sales tax / IVA / VAT — per-tenant configurable$kbf$, $kbf$Each tenant can turn on sales tax at their own rate. When
enabled, tax is calculated automatically on every public
booking and every quote approval, and stored separately on
` bookings.tax_cents` so it can be reported and
itemized on receipts.

Setup (one-time):

-
Go to `/admin/site` → scroll to the new
** Sales tax / IVA / VAT** section.

-
**Tax enabled**: Yes / No dropdown. Default: No.

-
**Tax rate percent**: decimal like
` 7.5` for 7.5%. Florida ≈ 7%, NY ≈ 8.875%,
CA ≈ 7.25–10.25%. Check your jurisdiction.

-
**Tax label**: how it shows to customers
("Sales tax", "IVA", "VAT").

Where it applies:

-
**Public booking** (`/order-by-date`):
tax is calculated on the taxable base (after discounts +
gift cards + points), added to the total, and saved on
the booking.

-
**Quote approval**: tax auto-calculates on
(line items + damage protection + power supply) at the
moment the customer approves. The live breakdown in the
setup form shows the tax row alongside the other extras.

-
**Admin quote editor**: the `Tax`
field stays — set it manually to override the auto-rate
for an exempt customer or an out-of-state event. If you
leave it at 0, the auto-rate fires at approval time.

Where to find collected tax for filing:

-
`/admin/reports` shows a "**Sales tax
collected (period to declare)**" section directly
under the P&L card. Shows total pre-tax revenue + tax
collected + customer-paid total + monthly breakdown.

-
The "Total revenue" summary card displays a subtitle like
`$X,XXX pre-tax + $YY.YY sales tax` when tax is
collected — so the headline figure is transparent.

-
**Tax collected CSV export** button in the
accounting section: per-booking detail rows with event
date, customer, product, pre-tax + tax + total. Last row
is a TOTAL summary. Drop straight into your sales-tax
return.

Two ways to exempt from tax:

-
**Per-product** — edit the product, tick "Tax
exempt" (or set `tax_exempt=true` in the bulk
CSV). The product's revenue counts toward the booking total
but is excluded from the taxable base. Use this for gift
cards, fees, or any non-taxable line. Shows up with a green
**TAX EXEMPT** badge in the customer's quote
view and the admin line items table.

-
**Per-customer (per-quote)** — tick the
**Tax exempt customer** checkbox next to the
Tax field in the quote editor. Skips tax on the WHOLE quote.
Use this for nonprofits, schools, gov, resellers with an
exemption certificate. Document the certificate # in
internal notes.

⚠️ This is a flat-rate tax. If you operate in multiple
jurisdictions with different rates by zip code, you'll need
to set the rate that covers your most common case and
handle exceptions per-quote.$kbf$, $kbf$Billing$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-setup-surfaces$kbf$, $kbf$Configurable setup surface options$kbf$, $kbf$The list of setup surfaces shown to customers (Grass, Dirt,
Concrete, etc.) is now editable per tenant. Manage them at the
bottom of `/admin/categories` in the new "Setup
surface options" section.

-
**Add** any surface you need (Sand, Wood Deck,
Indoor, etc.) — just a label and a lowercase internal value.

-
**Reorder** with the display_order field — lower
numbers appear first.

-
**Deactivate** options you don't use. Past
bookings keep their recorded surface; inactive ones just hide
from the public booking + quote forms going forward.

-
**Delete** when no longer relevant. Past bookings
keep their recorded value verbatim.

**Where it shows:** the public booking wizard's
"Setup surface" step *and* the quote approval form. Any
change reflects there immediately (next page load — no deploy
needed). Active surfaces only.

Defaults seeded for every tenant: Grass, Dirt, Concrete, Paver,
Asphalt, Other.$kbf$, $kbf$Setup$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-categories$kbf$, $kbf$Step 3 — Organize with categories$kbf$, $kbf$Categories group your products on the public website (e.g. "Bounce
Houses", "Slides", "Add-ons").

- Go to `Categories` → Add or Bulk upload

- Each category: name, optional image, display order, active flag

- "Active" categories show in public navigation; inactive are hidden

⚠ Category **"Add-ons"** is special: products in it (with is_addon=true)
are hidden from public catalog but available as upsells at checkout (chairs, tables, generator).$kbf$, $kbf$Catalog$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-fleet$kbf$, $kbf$Step 4 — Set up your fleet (vehicles + trailers)$kbf$, $kbf$Required for dispatch route planning.

- Go to `Fleet`

- Add each **Vehicle**: name, type (truck/van/pickup), needs trailer? capacity

- Add each **Trailer**: name, capacity

- Or use Bulk upload buttons

Later, when you plan dispatch routes for a day, you pick a vehicle and
(if it needs one) a trailer per route.$kbf$, $kbf$Dispatch$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-users$kbf$, $kbf$Step 5 — Add your team (staff + drivers)$kbf$, $kbf$3 roles available:

Role |
What they can do |

Admin |
Everything (you, owner) |

Staff |
Bookings, Customers, Inventory, Dispatch, Calendar, Availability |

Driver |
ONLY their day's routes (mobile-optimized) + capture proofs |

- Go to `Users` → **New user**

- Enter email, temp password, role

- Share credentials with the team member

- They log in at `/admin/login` → drivers auto-redirect to `/driver`$kbf$, $kbf$Dispatch$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-stripe$kbf$, $kbf$Step 6 — Connect Stripe for payments$kbf$, $kbf$Right now you're in **Stripe test mode**. For real payments:

- Wait for Stripe business verification approval

- Get live keys from Stripe Dashboard → Developers → API Keys

- In Vercel → Settings → Env vars:

<li>Update `STRIPE_SECRET_KEY` (starts with sk_live_)

- Update `NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY` (starts with pk_live_)

- Update `STRIPE_WEBHOOK_SECRET` (regenerate after pointing webhook to live)

</li>

- Redeploy from Vercel$kbf$, $kbf$Billing$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-emails$kbf$, $kbf$Step 7 — Email setup$kbf$, $kbf$Email delivery is included with your plan — RentalFlow handles the
sending. 10 automated emails go out automatically (booking
confirmation, reminders, quotes, etc.).

To customize email templates:

- Go to `Email templates`

- Click any template (e.g. "Booking confirmation")

- Edit subject, header, HTML body, plain-text fallback

- Use `{}`, `{}`, etc.

- **Preview** + **Send test** to yourself before saving$kbf$, $kbf$Communications$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-sms$kbf$, $kbf$Step 8 — SMS setup$kbf$, $kbf$SMS delivery is included with your plan — RentalFlow handles the
sending. SMS auto-sends for booking confirmation + reminder (3 days
before event).

If you don't see SMS going out, check the `Diagnostics`
page — if it says "SMS delivery: Not configured", contact RentalFlow
support and they'll enable it for your account.$kbf$, $kbf$Communications$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-loyalty$kbf$, $kbf$Step 9 — Loyalty + referrals$kbf$, $kbf$Customers earn points for bookings + commission for referrals.
Configure in `Website content → Loyalty & referrals`.

Points per $1 | 1 (default) |

Points → $1 | 100 (default) |

Referral commission | 10% of referred 1st booking |

Payout threshold | $50 (alert admin) |

Pay out commission manually via `Loyalty` → click customer → Record payout.$kbf$, $kbf$Promotions$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-coupons-gifts$kbf$, $kbf$Step 10 — Coupons + Gift cards$kbf$, $kbf$**Coupons** — discount codes. 3 types available:

- Go to `Coupons` → Add

- Pick a type:

<li>**Percent off** — e.g. 10% off the entire total

- **Fixed amount off** — e.g. $25 off in dollars

- **Overnight free** — waives ONLY the 30% second-day surcharge. Valid *only* for 2-day (overnight) rentals. Rejected with a clear message on 1-day or 3+ day rentals.

</li>

- Customer enters code at checkout

- Create `LOYAL10` → auto-shown to returning customers in /portal

💡 **"Overnight free" use case:** seed the OVERNIGHT
coupon (in `coupon_overnight_type.sql`) and advertise as
"free overnight upgrade — book 2 days, pay for 1". The discount
amount is calculated dynamically from the day-2 surcharge — you
don't enter a value yourself.

**Gift cards — admin issued** (you give one away or sell by phone):

- Go to `Gift cards` → Issue gift card

- Enter amount + recipient email

- System emails recipient the code automatically

- Recipient enters code at checkout in the 🎁 field

- Balance auto-decreases; remaining stays on the card

🆕 Customers can BUY gift cards online

Public page: `/gift-cards` (also in the nav as "🎁 Gift Cards").
Customer picks an amount ($10–$10,000), enters recipient info, pays via
Stripe, recipient gets the code by email automatically.

- Each online sale shows up in `Gift cards` like any other card

- Customer pays via Stripe → webhook issues the card → no manual work

- Purchaser gets a receipt email with the code (in case the recipient loses it)

Quick online/offline toggle per gift card:

In the gift cards table at `/admin/gift-cards`, the last
column has a **green/grey switch**. Click to disable
(customer can't redeem) or re-enable. Useful for fraud holds,
disputes, or expired-but-still-active cards. The toggle works in
both directions now — you can re-enable anything you disabled.

⚙️ Turn online sales ON or OFF

At the top of `Gift cards` you have a green/grey switch.

- **ON (default):** `/gift-cards` shows the buy form

- **OFF:** `/gift-cards` shows "Online sales paused — call us" with your phone. You can still issue cards manually from this page.

Use this if you ever need to pause sales (holiday cap, promo cooldown,
fraud concern) without removing the page from the site.$kbf$, $kbf$Promotions$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-payouts-w9$kbf$, $kbf$Step 10b — Referral payouts + W9 tax forms$kbf$, $kbf$When customers refer friends, they earn commission (see Step 9). They
can cash out from their `/portal/referrals` page. There are
** two payout types**:

🎁 Credit (no W9, auto-issued)

Customer chooses "rental credit" → on admin approval the system
auto-issues a gift card for the amount, emails them the code, and
moves the money from pending → paid. No tax form needed (it's not
a cash payment).

💵 Cash (Stripe / Venmo / Zelle — W9 required)

Customer chooses "cash payout" → must upload their W9 form
(PDF/JPG/PNG). The IRS requires a 1099-NEC at year-end if a
non-employee earns $600+ in cash from your business.

Your workflow when a request comes in:

- You'll see a yellow "Payout requests" panel at the top of `Loyalty`

- For cash requests: click **View W9 form** to open the PDF (signed link, valid 10 min)

- Click **Approve**:

<li>Credit → gift card auto-issued + emailed

- Cash → marked approved, waiting for you to pay externally

</li>

- For cash: send the money via Stripe/Venmo/Zelle, then click **Mark as paid** + enter the transfer ID/confirmation #

- Click **Reject** with a reason if the request isn't legitimate

🔒 W9 forms are stored securely

W9s contain SSNs, so they live in a **private** Supabase
bucket (`w9-forms`). They're NOT accessible by URL —
admins view them via short-lived signed links generated when you
click "View W9 form". The link expires in 10 minutes.

At year-end (before Jan 31), use these W9s to file 1099-NECs with
the IRS for any referrer who earned ≥$600 cash. The W9 has the SSN
+ legal name + address you need.

💡 Customers can re-upload their W9 anytime — the new file replaces
the old one and the upload date updates so you know which tax year
it applies to.$kbf$, $kbf$Billing$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-inventory-categories$kbf$, $kbf$Step 10c — Manage inventory categories$kbf$, $kbf$Inventory categories (Generators, Blowers, Tools…) live in the
` Manage inventory categories ` panel at the top of the
` Inventory ` page (admin only — click to expand).

- **Add** a category → it immediately shows up in the dropdown when creating/editing items

- **Rename** → the change cascades to every item that uses it (no orphans)

- **Hide** → keeps it on existing items but removes it from the dropdown (use for deprecated categories you don't want new items to land in)

- **Delete** → blocks if items are still using it. Confirm to reassign those items to "Other" then delete.

💡 This is different from `/admin/categories`, which controls
rental product categories that show on the public site. Inventory
categories are internal — customers never see them.$kbf$, $kbf$Catalog$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-reviews$kbf$, $kbf$Customer reviews + Google link$kbf$, $kbf$Reviews shown on the public site are curated manually — you decide
what appears. Manage them at `/admin/reviews`.

How it works:

- Copy the text of a review from Google/Facebook/Yelp/email

- In `/admin/reviews` click **Add review** → paste it, set name, rating, source, optional photo + date

- Toggle **Featured** to put it in the homepage carousel (limit 3 visible at a time, they auto-rotate every 7s)

- Toggle **Visible** off to hide without deleting

Where they show up:

- **Homepage carousel** above the trust strip — only "Featured + Active" ones, max 12 in rotation

- **/reviews page** — ALL active reviews, sorted Featured first, then most recent

- Linked from the public header (Info → Reviews)

💡 The **"Leave us a Google review"** CTA on both pages
uses the `google_review_url` setting (default points to
your maps.app.goo.gl link). Edit it in `/admin/site`
under the "reviews" category if your Google place ID changes.

💡 Phase 2 idea: auto-sync from Google Places API so new reviews
appear without manual copy-paste. Requires Google Cloud project +
API key + billing. Ask when you want to set this up.$kbf$, $kbf$Customer$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-coi$kbf$, $kbf$Certificates of Insurance (COI) for venues$kbf$, $kbf$Many venues (schools, parks, churches, HOAs, corporate offices)
require proof of insurance with them listed as additional insured
before they let you set up bounce houses on their property.

How the flow works:

- At checkout, customer checks **"My venue requires a Certificate of Insurance"**

- They fill venue name, address, who to list as additional insured, any special instructions

- On booking creation, a row is added to `coi_requests` with status **requested**

- You see the request in `/admin/coi` with all the venue details

- You call/email your insurance broker → they generate the COI PDF

- Back in `/admin/coi`, click **Upload COI**, attach the PDF

- Customer gets emailed automatically + the COI shows on their `/portal/bookings/[id]` page with a download button

- Optionally click **Mark delivered to venue** after you've sent it directly to the venue contact

Where to manage:

- `/admin/coi` — pending requests panel with upload

- Each booking detail page links to its COI request

- Disable the checkbox at checkout with the green/grey toggle at the top of `/admin/coi` (mirrors the Packages + Gift cards toggles)

💡 The PDF lives in your public Supabase storage (site-assets bucket).
That's fine — COIs aren't sensitive (they just name your insurance
carrier + policy number).$kbf$, $kbf$Policies$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-packages$kbf$, $kbf$Package deals (bundle multiple products at a fixed price)$kbf$, $kbf$Packages bundle several products into one fixed-price reservation
(e.g. "Birthday Premium = bouncer + slide + 2 tables + 12 chairs +
cotton candy for $549"). Customers see them on `/packages`
and reserve the bundle like one product — internally it reserves
the whole list.

Creating a package:

- `/admin/packages` → **+ New package**

- Fill name, slug (URL-safe), description, fixed price (dollars)

- **Image**: paste a URL OR click **Upload** to push a file directly to Supabase storage. Preview thumbnail appears below.

- In "Items in bundle": pick products from the dropdown, set quantities (e.g. 1× Game On bouncer, 6× folding chair, 1× cotton candy machine)

- Save → toggle **Active** to publish on /packages

Starter packages (8 pre-seeded — INACTIVE):

Running `supabase/seed_starter_packages.sql` creates 8
common packages (Birthday Classic, Premium, Tiny Tots, Splash,
Backyard Bash, Family Reunion, Corporate, Princess Tea). They come
with names + descriptions + suggested prices. **Items list is
empty** — you must edit each package and add YOUR products
before activating it. Toggle `is_active` to true once
configured.

⚠ The seed initially included Unsplash placeholder images, but
some IDs may not resolve. Run `supabase/fix_package_images.sql`
to clear them — then upload custom AI-generated images via the
editor's Upload button (recommended anyway for brand consistency).

Custom AI-generated images:

See `docs/package-image-prompts.md` in the repo — has
ready-to-paste prompts for Claude/DALL-E/Midjourney for each of the
8 packages, plus a brand style guide and template for new packages.
Generate → download → upload via the package editor's Upload button.

Uploading images:

- `/admin/packages/[id]` → "Image" field has an **Upload** button next to the URL input

- Accepts any image format (PNG, JPG, WebP, SVG)

- File goes to your Supabase storage `site-assets/packages/`

- Preview thumbnail appears below the field once uploaded

- URL field still works for manually pasting an externally-hosted image

Quick online/offline toggle (per package):

In the packages list at `/admin/packages`, each card has
a **green/grey switch** on the right. Click to toggle
between LIVE (visible on /packages publicly) and OFFLINE (hidden).
No need to enter the package detail — 1 click activates/deactivates.

🌐 Hide the ENTIRE Packages section from the public site

At the top of `/admin/packages` there's a big
**"Public Packages section ON/OFF"** switch.

- **ON (default):** /packages page works + "Packages" link visible in the header nav

- **OFF:** /packages shows "Coming soon — call us" with your phone. The "Packages" link disappears from the nav. Per-package toggles still work for when you turn it back on.

Same pattern as the gift cards toggle: nav link is hidden too
when the section is off, so customers don't see broken links.$kbf$, $kbf$Catalog$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-product-gallery$kbf$, $kbf$Product photo galleries (multiple photos per bouncer)$kbf$, $kbf$Each product can now have multiple photos. Customers see a carousel
on the product detail page (with thumbnails + click-to-zoom lightbox).
The "Image URL" field on the product form is still the **primary
cover** (used on cards/search); the gallery is additive.

To add photos:

- Go to `/admin/products/[id]`

- Scroll to the new **"Photo gallery"** section

- Click **Upload photo** (file picker) or **Add by URL** (paste link from elsewhere)

- Repeat for as many photos as you want

Per-photo actions in the grid:

- **← / →** arrows — reorder the photo within the carousel

- **⭐ star** — promote this gallery photo to be the primary cover (updates the product's main image_url, shown everywhere on the public site)

- **🗑 trash** — remove from gallery (also deletes from storage if uploaded)

💡 The primary cover shows a gold "Primary" badge in the gallery
grid so you always know which one is "the" image.

💡 Customer view: large image at top with hover ← → arrows, thumbnail
strip below, click main image to open full-screen lightbox with
keyboard arrow nav. No work needed on your end — it just works.$kbf$, $kbf$Catalog$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-per-day-consumables$kbf$, $kbf$Per-day consumables (propane, fuel, ice)$kbf$, $kbf$Some inventory items get *consumed* per day of rental — a
generator needs 1 propane tank per day, an ice chest needs 3 bags
of ice per day, etc. The system multiplies these automatically.

How to configure:

- Go to `/admin/products/[id]`

- In **Inventory checklist** → click **Add item**

- Select the consumable (e.g. "Propane tank 20lb")

- Enter qty **per day** (e.g. `1`)

- Check the box **"Per day (multiply qty × rental days)"**

- Save

What happens at booking time:

- 1-day rental → list shows **1 tank**

- 3-day rental → list shows **3 tanks**

- Truck load aggregation sums these multiplied quantities across all bookings on the route

- The reason column shows "1/day × 3 days" so it's transparent why the count went up

💡 Combine with "Only when needs Power Supply" so propane only
shows up when the customer actually rented power. Both checkboxes
can be active simultaneously.

💡 The blue "🗓 consumable" badge in the requirements list makes
it easy to spot which items will scale up vs static items
(anchors, cables, etc.).$kbf$, $kbf$Setup$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-unit-tracking$kbf$, $kbf$Per-unit asset tracking (which BLW-05 went where?)$kbf$, $kbf$For valuable items where you need to know *which physical unit*
was on which truck (blowers, generators, large bouncers), you can
tag each unit individually (BLW-01, BLW-02, ...) and assign specific
units to a route from dispatch.

One-time setup:

- Go to `Inventory` → click the item (e.g. "Blowers")

- Click **Enable unit tracking**

- Click **Bulk add (auto-tag)** → prefix `BLW`, count `14` → creates BLW-01 through BLW-14 instantly

- Optionally edit each unit to add serial number, acquired date, notes ("cracked housing", etc.)

- Physically label each unit with a sharpie / sticker matching its tag

Daily flow (per dispatch):

- Open `/admin/dispatch/[date]` → planned routes show the Truck Load section

- For each item that tracks units, you'll see "no units picked" + a **Pick units** button

- Click → modal lists every active unit with status dot (good / needs_repair / broken)

- Pick the specific units going on that truck → save

- The truck load card now shows tags like `BLW-03 BLW-07 BLW-11` instead of just "3× Blowers"

- Units assigned to another route on a different day are flagged red so you can't double-book

When a unit comes back damaged:

- Go to `Inventory` → item → find the unit → click pencil to edit

- Change condition to `needs_repair` or `broken`, add a note

- The status dot in dispatch dropdown will now show amber/red so you don't accidentally assign it again

💡 Don't enable unit tracking for high-volume consumables (sandbags,
cables, tarps). The overhead of picking specific units per route
isn't worth it. Reserve it for items you'd legitimately want to
trace ("which generator was at the Mendez delivery when it broke?").

💡 Phase 2 idea: driver scans QR codes printed on each unit to
confirm loading/return. Worth doing once you have 30+ tracked
units and crew rotation issues. Ask when ready.$kbf$, $kbf$Setup$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-weather-cancellation$kbf$, $kbf$Weather cancellation policy$kbf$, $kbf$Bounce houses can't run in unsafe weather (winds 15+ mph, lightning,
heavy rain). Instead of refunding cash (you lose revenue + your
crew's reserved day), the system auto-issues a **gift card
credit** for the full paid amount, valid 1 year.

How the flow works (customer side):

- Customer sees a blue "Bad weather forecast?" card on their `/portal/bookings/[id]` page — only up to **6 hours before** event start (configurable)

- They click → see the policy + the amount they'll get credited

- Confirm → booking is cancelled, gift card is auto-generated, email is sent with the code

What you (admin) see:

- The booking shows `cancelled` + flag `cancelled_due_to_weather=true`

- The gift card appears in `/admin/gift-cards` with note "weather cancellation credit"

- An audit line is appended to the booking notes

Tune the policy:

- `weather_cancellation_enabled` — true/false to allow self-service at all

- `weather_cancellation_cutoff_hours` — default 6. Increase to 24 to close the option the day before. Decrease to 2 if you want last-minute decisions allowed.

- `weather_cancellation_policy_text` — full policy shown to customer in the confirmation dialog

💡 After the cutoff, the option disappears and customers must call
you. That's intentional — gives YOU the judgment call when it's
within hours of the event.$kbf$, $kbf$Policies$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-waiver$kbf$, $kbf$Liability waiver e-signature (legal)$kbf$, $kbf$Every customer signs a liability waiver at checkout. The waiver text
you have set in `/admin/waiver` is what they see and what
gets snapshotted per booking (so editing it later doesn't change
past signatures — keeps them legally defensible).

⚠ Get this reviewed by a Florida attorney before going live

The default text is built from common bounce-house industry
language but isn't legal advice. Wrong wording can be unenforceable
under Florida law.

Where to manage it:

- `/admin/waiver` — edit text, toggle on/off, see signed count

- `/info/waiver` — public page customers can save/print before booking

- Linked from the public site footer alongside Privacy/Terms

What gets recorded per signature:

- Booking ID + customer's full legal name (typed)

- Email + IP address + browser user agent

- Exact waiver title + text shown at that moment

- Timestamp

💡 If you ever need a defensible record for a claim, query the
` booking_waivers ` table by booking_id — every field is
captured. Future enhancement: download as PDF directly from the
booking detail page.$kbf$, $kbf$Policies$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-fleet-compatible-items$kbf$, $kbf$Fleet: mark which trucks can carry special gear$kbf$, $kbf$Some inventory items (electric dolly, ramps, lifts, oversized cargo)
only fit certain vehicles/trailers. Mark which fleet units are
equipped to carry what so you can spot mismatches before sending
the wrong truck.

Setup (per vehicle/trailer):

- Go to `/admin/fleet`

- Click pencil on a vehicle or trailer

- In **Can carry / mount (special inventory)** section, check the items this unit can physically carry (electric dolly, ramps, etc.)

- Save

Where it shows up:

- Fleet table has a new **"Can carry"** column with blue tags showing each unit's compatibilities at a glance

- When planning dispatch, glance at the assigned truck's tags vs the truck load — if the load needs the dolly but the truck doesn't have it tagged, pick a different truck

💡 Combine with per-unit asset tracking (BLW-01...): the truck
load shows specific tags AND the truck's compatibility list, so
you have full visibility into what's loaded + whether the truck
can actually carry it.$kbf$, $kbf$Dispatch$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-fleet-vin-tag$kbf$, $kbf$Step 10d — Fleet: VIN + license tag$kbf$, $kbf$Each vehicle and trailer in `Fleet` can store its
** License tag** (plate #) and **VIN**.
Both are optional but useful for insurance claims, traffic stops,
DMV renewals, and identifying which truck to take.

- Go to `Fleet`

- Click **Add vehicle / trailer** or the pencil to edit one

- Fill **License tag** and/or **VIN** — they auto-uppercase + trim

- Save. The columns now show on the Fleet table for quick lookup.

💡 Bulk upload supports both fields too — download a fresh
` vehicles ` or ` trailers ` CSV template from
the top of this Help page.$kbf$, $kbf$Dispatch$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-site-font$kbf$, $kbf$Step 11a — Change the site font (Louis George Cafe etc.)$kbf$, $kbf$The entire public site uses one global font. Change it from
`/admin/site` → top of the **Appearance**
section → "Site-wide font" picker.

Free presets (load instantly from Google Fonts CDN):

- **Quicksand** — recommended. The free Google Fonts twin of Louis George Cafe (rounded geometric sans-serif, brand-friendly for kids/family events).

- **Nunito**, **Poppins** — similar rounded sans-serif vibe

- **Inter**, **Montserrat** — clean modern sans-serif

- **Playfair Display** — elegant serif if you want a more upscale feel

Custom: type any Google Font

Pick "Custom (type your own)" → enter the family name + paste the
Google Fonts stylesheet URL (from fonts.google.com → pick font →
"Get embed code" → copy the href).

Louis George Cafe (self-hosted, brand-exact)

✨ **New:** NO need to edit code or redeploy anymore.
Pick "Louis George Cafe (self-hosted)" in the picker → click
**Upload Louis George Cafe (.woff2)** button →
select the .woff2 file you downloaded from 1001fonts.com → Save
settings. The picker handles everything: uploads to Supabase,
stores the URL, emits the right @font-face automatically.

License note: 1001fonts.com offers LGC free for personal use; some
font licenses require purchase for commercial use. Verify your
license before going live commercially — or stick with
**Quicksand** (SIL Open Font License, free for any
use, looks ~95% identical to LGC).

💡 Per-zone fonts (in the Appearance section below) still work and
OVERRIDE the global font for specific sections. Most people use only
the global setting and leave per-zone empty.$kbf$, $kbf$Customization$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-site$kbf$, $kbf$Step 11 — Customize the public site$kbf$, $kbf$Go to `Website content` to edit ALL public copy + colors:

- Hero title + subtitle

- Section titles

- Trust strip copy

- Footer description

- Per-zone colors + fonts (Hero, Categories, Featured, Trust, Footer)

Go to `Home banners` to upload carousel images (1920×600 recommended).$kbf$, $kbf$Customization$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-contact-inbox$kbf$, $kbf$Contact form inbox — where messages land$kbf$, $kbf$Every submission from the public `/contact` page goes
through three channels simultaneously so a message can't slip
through the cracks:

- **Saved to DB** (`contact_messages`) — source of truth, always works

- **Emailed to admin** → goes to your configured admin alert email. Reply-to is set to the customer's email so hitting Reply goes straight to them.

- **Pushed to GHL** via webhook → workflow 1 creates/updates the contact with tag `general_inquiry`

Manage from `/admin/inbox`:

- Open messages show at the top; resolved ones at the bottom (greyed out)

- Click **Reply** to open your email client pre-addressed to the sender

- Click **Mark resolved** after handling, optionally add a note ("called back, booked")

- Green/red badges show delivery status per channel (email ✓ / GHL ✓). If GHL failed, you'll see the error — message is still safe in DB.

- Admin can **Reopen** or **Delete** any message

💡 The "Delivery issues" stat at the top counts unresolved messages
where email or GHL didn't go through — those are the ones to
handle first. When a delivery fails, you'll see a **red banner
inside the message card** with the exact email/GHL error
(no need to dig in deployment logs).

💡 New unresolved messages also show as a **red alert panel
on the Dashboard** (top 5 with sender, subject, badge). The
"X need attention" pill in the header counts them.

📥 Optional: receive emails to your own address directly in the inbox

Want customer replies (and direct emails to e.g.
`bookings@yourdomain.com`) to land in
`/admin/inbox` automatically? This needs a small
one-time setup. Contact RentalFlow support and we'll walk you
through it — takes about 10 minutes if your domain is on
Cloudflare DNS.

Replying directly from the inbox:

- Click **Reply** → inline composer opens (no need to leave the app)

- Type the reply in plain text — blank lines become paragraphs

- Customer receives a clean HTML email from your configured sender address with your message, sign-off, and the original collapsed at the bottom

- **Reply-To is set to your email** so if they reply, it goes to your inbox

- Check **"Mark resolved after sending"** to close the message in one click

- Every reply is logged in the message's thread (sent_by + timestamp), so staff can see what was already said before replying again

- If email delivery fails, the reply still saves to the log with the error — you can copy the text and resend manually$kbf$, $kbf$Customer$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-customer-tracking$kbf$, $kbf$Customer tracking page (Domino's-style timeline)$kbf$, $kbf$Every customer booking detail page at `/portal/bookings/[id]`
now shows a 6-step visual timeline that updates in real time as the
booking moves through its lifecycle. No more "where's my rental?"
phone calls.

The 6 steps:

- ✅ **Payment confirmed** — green check once Stripe clears

- ⏳ **X days until your event** — countdown with context-aware copy ("we'll send a reminder 3 days before" / "your event is tomorrow!")

- 📦 **Loaded on the truck** — activates when admin marks the route as `loaded` in /admin/dispatch. Shows driver + vehicle name.

- 🚚 **Driver on the way** — activates when route status is `out_for_delivery`

- ✨ **Delivered & set up** — when delivery stop is marked completed

- 📅 **Picked up** — when the pickup route is completed

The active step pulses with a yellow ring; done steps are green
with strikethrough. Special states handled: cancelled bookings
short-circuit to a single "Cancelled" card; weather cancellations
show the credit message.

💡 To make the timeline progress through "loaded" and "out for
delivery", you (admin) need to update the `dispatch_routes.status`
field as the day goes on — in `/admin/dispatch/[date]` there
should be a status dropdown per route.$kbf$, $kbf$Customer$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-extend-rental$kbf$, $kbf$Customer extends rental from portal (self-service)$kbf$, $kbf$On the customer's portal booking detail, an amber "Extend rental"
card lets them add days to an active booking. The customer picks
a new end date, the system validates availability + computes the
additional cost (30% per added day, honoring weekend rates), then
charges them via Stripe.

Validation rules:

- Booking must be PAID (no extensions on unpaid)

- Not cancelled or completed

- New end date must be AFTER current end date

- Total rental can't exceed 14 days

- Each new day must be available (no conflict with other bookings or blocked dates)

- Cutoff: must request at least 6 hours before event start

Payment flow:

- Customer picks new end date → "Check price"

- System creates a row in `booking_extensions` (pending) + Stripe PaymentIntent

- Stripe Elements appears inline → customer pays

- Webhook fires `payment_intent.succeeded` with `metadata.type=booking_extension`

- Webhook bumps `bookings.event_end_date`, adds to `total_amount`, appends audit line to notes

- Customer's tracking timeline updates with the new end date

💡 Extension rows in `booking_extensions` table give you a
clean refund target if needed — refund the extension PaymentIntent
directly without touching the original booking charge.$kbf$, $kbf$Customer$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-quote-followup$kbf$, $kbf$Quote follow-up reminder (auto)$kbf$, $kbf$Quotes sent but not accepted often sit in a customer's inbox and
get forgotten. A daily cron at 4 PM EST finds quotes that are
**3+ days old, still in 'sent' or 'viewed' status, not
expired** — and emails a friendly reminder with a big
"View and Accept" button.

Logic:

- Runs daily at 16:00 UTC (cron in vercel.json)

- Only sends ONE reminder per quote (followup_sent_at marks it)

- Skips paid, declined, or expired quotes

- Up to 50 reminders per run (cap to avoid bursts)

- Email tagged as `quote_followup` for analytics

💡 To trigger manually for testing:
`curl -H "Authorization: Bearer $CRON_SECRET" https://itsalwaysfun-rental.vercel.app/api/cron/quote-followup`$kbf$, $kbf$Setup$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-quote-approval-flow$kbf$, $kbf$Quotes — approval flow + 24h hold + payment reminder$kbf$, $kbf$Full picture of what happens between a quote being sent and
payment confirming.

1. Admin creates the quote

-
**Existing customer dropdown** at the top of the
Customer section — auto-fills name, email, phone, address from
past bookings.

-
**Customer message** pre-fills from your site
settings (business name, service area, social handle, public
URL). Edit freely or "↺ Reset to default template".

-
**Customer choices on approval** section — you
only decide what to OFFER:

<li>
☐ Offer damage protection on this quote (+ price snapshot).
The customer chooses yes/no.

-
☐ Require liability waiver signature before payment
(defaults ON).

</li>

-
Surface type + power source are NOT here — the customer fills
those when they approve.

2. Customer receives quote → clicks "Approve quote"

A setup form appears with (in order):

- Setup surface (grass/dirt/concrete/paver/asphalt/other) — required

- Power source (has outlet / bring generator) — required

- Damage protection accept/decline (only if you offered it)

- Liability waiver text + checkbox + typed-name signature (only if you required it)

On "Approve & continue to payment": system runs an availability
check on the primary product. If still available, creates a
booking with a **24-hour hold** and proceeds to
Stripe Elements. If someone reserved the same date in the
meantime, returns "Sorry, no longer available" — first to
approve wins.

3. Hold + payment window

-
The booking blocks inventory for 24 hours after approval. Other
customers can't book the same product/date during that window.

-
If payment completes (Stripe webhook) → booking becomes
`confirmed` and the hold becomes permanent. Quote
status → `converted`.

-
If 24h pass without payment → the hold expires automatically.
The inventory becomes available to other customers again. The
booking row stays but is no longer counted as occupying the slot.

4. Hourly reminder cron (auto)

`/api/cron/quote-hold-reminder` runs every hour and
finds approved quotes whose 24h hold is about to expire (within
the next 6 hours), payment hasn't completed, and no reminder was
sent yet.

Sends the customer a "Your reservation expires in Xh — complete
payment to lock it in" email with quote total + expiry timestamp
+ payment link.

Idempotent via `quotes.hold_reminder_sent_at`. Email
tagged `quote_hold_reminder` for analytics.

5. Customer returns after hold expired

-
When the customer lands on the public quote page (their unique
magic link), if the 24h hold already expired and the booking
is still pending payment → the system runs the availability
check again across ALL line items.

-
If everything is still free → extends the hold by 1 hour so
the customer has time to complete payment via Stripe.

-
If anything got booked in the meantime → shows a red banner
"This reservation is no longer available" and hides the
payment button. The customer is asked to contact you for
alternative dates or substitute items.

**Multi-product quotes — full availability check + hold:**

All secondary line items (and the power supply if requested) are
written to `bookings.addons` when the quote is approved.
The availability check counts occupied inventory from BOTH each
booking's `product_id` AND items inside each booking's
`addons` array. So a 24h hold from a quote now blocks
every product in the bundle — not just the primary item. This also
means addons booked through the public flow (chairs, tables,
generators) get counted correctly against stock.

**Auto-priced power supply + damage protection:**
When the customer says they need a generator during approval, the
system looks up the `power-supply` add-on product
(must have `slug="power-supply"` and
`is_addon=true`) and adds price-per-day × number of
rental days to the total. Damage protection does the same with the
quote's snapshot price. The setup form shows a live breakdown
("Original quote $X + Damage protection $Y + Power supply $Z =
Total $T") and the final "Approve & pay" button displays the
full amount they're about to charge.

**Per-tenant requirement:** for power supply pricing
to fire, each tenant needs a product in their catalog with
`slug="power-supply"` + `is_addon=true` +
`is_active=true`. If missing, the booking still records
"customer needs generator" in the dispatch notes but no auto-charge
is added — you handle pricing manually.

**Editable reminder email:** the 24h hold reminder is
now an editable template at
`/admin/email-templates` with key
`quote_hold_reminder`. Available merge vars:
`firstName`, `brandName`,
`quoteNumber`, `totalDollars`,
`quoteUrl`, `expiryLabel`,
`hoursLeft`, `hoursLeftPlural`. If the
template is missing from the DB, the cron falls back to a
hardcoded version with the same content.$kbf$, $kbf$Billing$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-audit-log$kbf$, $kbf$Audit log — who did what, when$kbf$, $kbf$Every sensitive admin action is recorded automatically in
`/admin/audit-log` with: who did it (email), what they
did (action name), what entity (booking/gift card/payout/etc.),
when, IP address, and a JSON details blob with the relevant context
(amounts, codes, customer email, etc.).

What gets logged today:

- `booking.refunded` — admin refunded a paid booking (amount, method, Stripe refund ID, customer)

- `payout.approved.credit` — referrer payout approved as gift card credit

- `payout.approved.cash` — referrer payout approved as cash (W9 required)

- `gift_card.deactivated` / `.reactivated` — code disabled or re-enabled

Filter by user email, entity type, or action contains text. Last
500 events kept (older ones auto-rotate). Staff only see their own
actions; admins see everyone's.

💡 Use cases: investigate "who refunded that booking?" — search by
customer email or booking ID. Comply with audit requests from
insurance / IRS. Track if a new staff member is making mistakes.

💡 More actions can be hooked into the audit log easily — ask if
you want to track other things (e.g. customer cancellations from
portal, product price changes, user role changes).$kbf$, $kbf$Operations$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-error-monitoring$kbf$, $kbf$Error monitoring — RentalFlow catches bugs for you$kbf$, $kbf$RentalFlow watches your app 24/7 for crashes — both browser-side
(a customer clicks something and gets an error) and server-side
(booking creation fails, email sends throw exceptions). When
something breaks, our team gets notified automatically so we can
push a fix without you having to report it.

💡 You don't need to set anything up — this comes with your plan.
If you suspect something is broken, just contact support and we'll
check the logs.$kbf$, $kbf$Operations$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-pwa$kbf$, $kbf$Driver mobile app (PWA — install on phone home screen)$kbf$, $kbf$The driver view at `/driver` can now be installed on
phones as an app — icon on home screen, full-screen mode (no
browser bar), offline support for venues with bad signal.

Driver onboarding (one time per phone):

- Driver opens `https://itsalwaysfun-rental.vercel.app/driver` in their phone browser

- **Android (Chrome)**: a navy banner appears bottom of screen — "Install the driver app" → tap **Install** → done

- **iPhone (Safari)**: same banner shows iOS-specific instructions — tap Share button → "Add to Home Screen"

- App icon "IAF Driver" appears on home screen — tap to open in standalone mode

What it does:

- Opens full-screen (no URL bar / tabs) — looks like a native app

- Loads in <1 second after first install (cached)

- Routes + booking data work offline (cached); marking stops, photos, signatures sync when signal returns

- Auto-updates when you deploy changes — driver never needs to reinstall

- Customer portal + admin pages also installable (same manifest covers the whole app)

⚠ **For best icon branding:** upload 3 PNG files to
`public/icons/`:
`icon-192.png · icon-512.png · icon-180.png`
Use <a>realfavicongenerator.net</a> to generate
them from your logo. Without these the PWA still works — just uses a
generic browser icon. See `public/icons/README.md` in the
repo for details.

💡 The install prompt remembers if the driver dismissed it for 7
days so they're not nagged. After 7 days it shows again.

💡 PWA is built on the same domain — no Apple Developer account or
Google Play submission required. Drivers can install it free in
seconds from the website.$kbf$, $kbf$Dispatch$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-realtime$kbf$, $kbf$Live notifications — bookings, messages, payouts, COI$kbf$, $kbf$The admin gets **instant push notifications** via Supabase
Realtime when key things happen — no need to refresh the page. A toast
pops up in the top-right corner and the relevant list/dashboard
auto-refreshes.

What triggers a notification:

- 📨 **New contact message** (form submission OR inbound email to bookings@) — shows sender + subject

- 📅 **New booking** — shows customer + product + event date. Differentiates between PAID (💰) and pending payment.

- 💵 **Payout request** from a referrer — shows amount + type (credit / cash)

- 📄 **COI request** at checkout — shows venue name

Each toast has a **Refresh** button if you want to
jump straight to the updated data. Toasts auto-dismiss after 6
seconds.

💡 Notifications work across ALL admin pages — leave the dashboard
open in one browser tab while you work elsewhere; new events still
pop on top of whatever page you're viewing.

⚙️ **Setup required (one time):** run
`supabase/realtime_publication.sql` in the Supabase SQL
editor to enable Realtime broadcasts on the 4 tables. Without it
the dashboard works fine, just no live push.$kbf$, $kbf$Billing$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-dispatch-mirror$kbf$, $kbf$Dispatch: pickup route auto-mirrors delivery$kbf$, $kbf$When you assign a booking to a **delivery** route, the
system now automatically creates (or finds) a matching
**pickup** route on the booking's end date — using the
same vehicle, trailer, and driver as the delivery — and assigns the
booking there too. No more building pickup routes manually for every
day.

How it works:

- Assign Booking A to Delivery Route X (Truck 1, John)

- System checks Booking A's `event_end_date`

- If a pickup route on that date with Truck 1 exists → adds Booking A as a stop

- If not → creates a new pickup route (same Truck 1, John, etc.) + adds Booking A

- Toast confirms: "Assigned + pickup route auto-created for 2026-06-15"

When the auto-mirror is SKIPPED:

- Booking already has a manually-assigned pickup stop (respects your override)

- You're assigning to a pickup route directly (no delivery to mirror from)

- If anything errors during mirror → silent skip (delivery assignment never blocked)

When you need to change pickup manually:

Go to the pickup date's dispatch page → find the auto-created route
(notes say "Auto-created from delivery route") → reassign the
booking to a different route, or change the vehicle/driver on the
auto route itself.

💡 For 1-day rentals (event_end_date = event_date), the pickup route
is created on the same day. You'll see TWO routes on that date —
one delivery (morning), one pickup (evening).$kbf$, $kbf$Dispatch$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-daily-ops$kbf$, $kbf$Daily operations — what to do each day$kbf$, $kbf$Morning routine:

- Open `Dashboard` → see alerts (pending payments, damages, payouts)

- Open `Calendar` or `Bookings` → review today's events

- Open `Dispatch → today's routes` → make sure drivers know assignments

Day before each event:

- `Dispatch → Plan tomorrow` → create routes + assign bookings

- Each route shows aggregated truck load (what to bring)

- Send driver the **Driver view** link via WhatsApp

After event (pickup day):

- Driver captures pickup proof + records any damages

- Admin reviews damages in `Bookings → [id]` → mark customer responsible / covered by protection / charged$kbf$, $kbf$Setup$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-backups$kbf$, $kbf$Backups — manual + weekly automatic$kbf$, $kbf$Two-layer DB backup beyond Supabase's built-in plan backups:

1. Manual on-demand (any time)

`/admin/diagnostics` → scroll to the blue "Backups" card →
click **"Download backup now"**. Generates a JSON file
with every critical table (bookings, expenses, customers, products,
settings, etc.) + auth user metadata. Saves to your Downloads
folder as `iaf-backup-YYYY-MM-DD.json`.

Use it before any risky change ("about to mass-edit products → let
me backup first") or for ad-hoc archival.

2. Weekly automatic (cron)

Every Sunday 3 AM UTC, the cron at `/api/cron/weekly-backup`:

- Generates the same JSON dump

- Uploads to the private `backups` Supabase Storage bucket

- Prunes files older than 84 days (~12 weeks)

- Emails you (ADMIN_ALERT_EMAIL) a 7-day signed download link

All scheduled backups are visible in the "Backups" card on
diagnostics (file list with sizes).

💡 Need a backup right now (off-cycle)? Contact RentalFlow support
and we can run it on demand.

⚠ **Setup required (one time):** run
`supabase/backups_bucket.sql` to create the private
`backups` bucket. Without it the cron's upload step fails
(manual download still works without the bucket).

⚠ **Doesn't include uploaded files** (waivers PDFs, COI files,
W9s, product photos, gift card backgrounds). Those live in Supabase
Storage and are managed by Supabase's own bucket lifecycle. On Free
plan there's no automatic bucket backup — consider upgrading to Pro
($25/mo) for full Supabase-managed backups.$kbf$, $kbf$Operations$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-billing$kbf$, $kbf$Billing — invoices, card on file, next charge$kbf$, $kbf$`/admin/settings/billing` shows everything about your
RentalFlow subscription (separate from Stripe Connect — which
handles customer payments to your bank).

What's there:

-
**Current subscription card** — plan, status,
next renewal date. "Manage" button opens Stripe's hosted
billing portal where you can cancel, change plan, update
billing email, etc.

-
**Next charge** — exact amount + date of the
upcoming invoice. Cancels show "No future charges".

-
**Paid this year** — running total of paid
invoices in the current calendar year. Useful when
deducting RentalFlow as a business expense at tax time.

-
**Payment method on file** — card brand + last 4
+ expiry, with red/amber alerts if expired or about to
expire. "Update card" opens Stripe's secure portal — we
never store your card number.

-
**Invoice history** — last 12 invoices with
date, billing period, amount, status pill, and a "PDF"
download link straight from Stripe.

🔒 RentalFlow never stores your card. The "Manage" / "Update
card" buttons all redirect to Stripe's PCI-compliant portal;
after you're done there, you come back here.$kbf$, $kbf$Billing$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-diagnostics$kbf$, $kbf$System diagnostics (health check)$kbf$, $kbf$`/admin/diagnostics` is a one-click health check that
verifies your environment is wired correctly before you run real
tests or launch. Admin-only.

What it checks (≈25 items, grouped):

- **Environment** — Stripe mode (live vs test) + key parity, Webhook secret, Email delivery, Admin alert email, App URL, Cron secret, GHL webhook, SMS delivery, Error monitoring, Inbound email secret

- **Database tables** — existence + row counts for all critical tables (bookings, products, inventory, audit_log, accounting tables, 1099-NEC tables, etc.). Catches missing migrations.

- **Site settings** — required keys present (driver rate, 1099 threshold, low-stock email, damage protection toggle, lead time, etc.)

- **Data state** — at least 1 active product, 1 active fleet, 1 admin user; warns if 0 low-stock thresholds set or 0 overhead recorded

- **Cron health** — recent audit_log activity, last inbound email worker hit, count of failed email deliveries

How to read the output:

- **🚨 Blockers** (red) — fix before launching / testing. Bookings, payments, or core features will fail.

- **⚠ Warnings** (amber) — not blocking but worth fixing (e.g., SMS delivery not enabled for your account)

- **OK** (green) — verified working

- **Info** (grey) — informational counts, not a pass/fail check

💡 Run this BEFORE your first real Stripe charge to confirm live keys are
in place. Run it AFTER every redeploy if you changed env vars.
Run it monthly as a sanity check.$kbf$, $kbf$Operations$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-1099-nec$kbf$, $kbf$1099-NEC year-end report (contractor tax filing)$kbf$, $kbf$The IRS requires a 1099-NEC for every non-employee paid
**$600 or more** in a calendar year. This page does the
compilation work for you so January doesn't become a scramble.

Where to find it:

`/admin/reports/1099-nec` — also reachable via the green
"1099-NEC year-end →" button on `/admin/reports`.

How it works:

- Sums every booking expense where the category has the
**supports_payroll_hours** flag (payroll, setup_labor,
teardown_labor, or any custom labor category) — grouped by
`driver_email` — for the selected calendar year

- Each row shows: total paid, hours, bookings, W9 status, TIN last 4,
address completeness, filed status

- Qualifying drivers (≥ threshold) are shown first; non-qualifying
ones below for reference

- The 5-stat header tracks: drivers w/ payments, qualifying count,
total paid out, missing W9 count, filed progress

January workflow:

- Switch to the closing tax year (year selector at top)

- For each qualifying driver missing W9, name, TIN, or address:
click **Profile** to fill it in, click **W9**
to mark received

- Download CSV → upload to your filing service (Track1099,
eFile4Biz, or hand to accountant)

- After each filing, click **Mark filed** so you can
track progress at a glance

- IRS deadline: **January 31** for both recipient copy +
IRS filing

💡 **TIN storage:** only the last 4 digits are stored in
the DB (for verification). The full SSN/EIN lives in the W9 PDF in
private Supabase storage (bucket: `w9`). Never paste a
full SSN into the notes field.

💡 The $600 threshold is configurable in
`site_settings.1099_nec_threshold_cents` — change it if
the IRS raises the limit.

⚙️ **Setup required (one time):** run
`supabase/driver_1099.sql`. Creates the
`driver_tax_profiles` table and seeds the threshold
site setting.$kbf$, $kbf$Billing$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-reports-advanced$kbf$, $kbf$Advanced reports — cash flow, monthly trends, drivers, LTV$kbf$, $kbf$`/admin/reports` now has four advanced cards beyond the P&L
summary. They appear in this order:

1. Cash flow projection (next 90 days)

Bucketed into **Next 7d / 8–30d / 31–60d / 61–90d**. For
each bucket: confirmed (paid) vs pending payment in dollars, plus
booking counts. Stacked bar chart shows distribution at a glance.

Use it to: plan staffing for busy weekends, see if the rest of the
month is going to be slow (run a promo), spot when pending bookings
are too high (chase those payments).

2. Monthly P&L (last 12 months side-by-side)

One column per month: Bookings count, Revenue, − Direct costs,
= Gross profit, − Overhead, = NET. Plus a Total column on the right.
Independent of the date filter (always trailing 12 months).

Use it to: spot seasonality (which months are profitable vs which
burn cash), see if margins are improving month over month, identify
outlier months that need investigation.

3. Top drivers / crew (labor hours in date range)

Sums any booking expense whose category has the
**supports_payroll_hours** flag (payroll, setup_labor,
teardown_labor, or any custom you add), grouped by
`driver_email`. Shows hours, payroll $, $ per hour,
bookings count.

Use it to: prepare payroll runs (export the date range, pay each
driver), spot top performers, prep 1099-NEC year-end totals (set
the range to YTD).

⚠ This only shows drivers when the `driver_email` field is
filled on the expense. Make sure your team fills it when recording
payroll on a booking.

4. Customer LTV (lifetime value, top 25)

All-time totals per customer. Shows bookings, lifetime revenue,
avg per booking, first/last booking date, days since last, plus a
status badge:

- 🐳 **Whale** — top 3 by LTV with 2+ bookings

- **Active** — booked in last 90 days + repeat

- **Returning** — repeat customer

- **One-time** — single booking on record

- **Lapsed 1yr+** — booked once but hasn't in over a year (great win-back targets)

Use it to: send a personal thank-you to whales, win-back coupons to
lapsed customers, mass-tag active customers in GHL for VIP campaigns.$kbf$, $kbf$Dispatch$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-low-stock$kbf$, $kbf$Inventory low-stock alerts (auto)$kbf$, $kbf$Each inventory item can set a **Low-stock alert at ≤**
threshold (in the item form). A daily cron at 1 PM UTC scans every
active item and emails the admin if
`(quantity_owned - quantity_in_use) ≤ threshold`.

Smart re-alert logic:

- You only get ONE email per item per low-stock event

- Once you restock above the threshold, the alert flag resets — next time it dips below you get a fresh alert

- 0 (default) disables the alert for that item

Where alerts appear:

- **Email digest** — grouped by category, shows available/owned, threshold, location. Goes to `low_stock_alert_email` site setting (or `ADMIN_ALERT_EMAIL` env var if blank)

- **Amber banner on /admin/inventory** — always-on, shows ALL items currently below threshold (not just newly-low). Updates live whenever you refresh the page.

- **Per-row "low" badge** in the inventory table — amber AlertTriangle next to the available count

💡 To trigger manually for testing:
`curl -H "Authorization: Bearer $CRON_SECRET" https://itsalwaysfun-rental.vercel.app/api/cron/low-stock-alert`

⚙️ **Setup required (one time):** run
`supabase/inventory_low_stock.sql` in the Supabase SQL editor.
This adds `low_stock_threshold` + `low_stock_alerted_at`
columns to `inventory_items` and seeds the `low_stock_alert_email`
site setting.$kbf$, $kbf$Catalog$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-accounting$kbf$, $kbf$Accounting — true profit per booking + monthly overhead$kbf$, $kbf$Most rental businesses look at booking **revenue** and call it a
day. To know your **real** profit you also need: (a) the
direct costs of running each event (gas, payroll, tolls, propane,
damage repairs) and (b) the fixed monthly burden you carry whether
you book or not (rent, insurance, software, vehicle payments). The
accounting module gives you both.

1. Direct costs per booking

Open any booking in `/admin/bookings/[id]` — there's now a
**Costs for this booking** card under Damages with a live
margin summary (Revenue / Direct costs / Gross margin). Click
**+ Add expense**:

- ⛽ **Gas / fuel**, 🛣 **Tolls**, 📦 **Consumables** (propane, ice, batteries), 🔧 **Damage repair**, 📋 **Permit / venue fee**, 🧼 **Cleaning fee**, 🅿️ **Parking**, 🏨 **Lodging**, 🗂 **Other** — type description + amount

- 👥 **Payroll (driver hours)**, 🔨 **Setup labor**, 🧹 **Teardown labor** — enter the hours; the form auto-suggests the dollar amount from the default driver hourly rate (set as `default_driver_hourly_rate_cents` in site_settings, defaults to $20/hr). Optionally tag a driver email for payroll attribution.

- Click **Categories** next to the Add expense button to manage the list — add new categories (e.g. "Vehicle rental"), edit labels, deactivate ones you don't use. Categories with the labor-hours flag show the hours UI automatically.

Every expense is logged in the audit log (`expense.gas`,
`expense.payroll`, etc.) with the admin email + amount, so
you have an immutable record for tax season.

2. Monthly overhead

Go to `/admin/overhead` (admin-only nav entry). Add one
line per fixed monthly cost. The category dropdown is
**fully editable** — click *Manage categories*
at the top to add/edit/deactivate categories. Seeded with ~36
standard chart-of-accounts categories grouped by:

- **Occupancy** — Rent, Storage/warehouse, Utilities, Phone/internet

- **Insurance** — General liability, Vehicle, Workers comp, Property/equipment

- **Vehicles & equipment** — Vehicle payments, Vehicle maintenance, Equipment maintenance, Equipment lease, Depreciation

- **Personnel** — Salaried payroll, Payroll taxes, Benefits

- **Professional** — Accountant, Attorney, Consultants

- **Financial** — Merchant fees (Stripe %), Loan/debt service, Interest, Bank fees

- **Marketing** — Advertising, Listings (GigSalad/The Bash), Print/signage, Trade shows

- **Software** — SaaS subs, Memberships/dues (Chamber, IAAPA), Training

- **Operations** — Permits/licenses, Office supplies, Cleaning supplies, Uniforms, Travel/mileage, Meals

- **Taxes (recurring)** — Property tax, Franchise tax, Business license tax

- **Other** — catch-all

Each item has an **Effective from** date (when the cost
started) and optional **Effective to** (if it ended — use
the *End* button on the row). Cost changes are recorded as new
rows so you have history (e.g. insurance went from $400 → $450 in
Feb). Deactivating a category just hides it from the dropdown —
historical overhead rows that used it stay intact.

3. Profit & Loss report

`/admin/reports` now shows a yellow-bordered
**Profit & Loss** card at the top, scoped to the
same date range as the rest of the page:

- **Revenue** — paid bookings whose event_date falls in range

- **Direct costs** — sum of all booking_expenses for those bookings, broken down by category

- **Gross profit** — Revenue − Direct costs (with % margin)

- **Overhead allocated** — monthly overhead prorated by days the cost was active during the period (e.g. $1500/mo over 30 days = $50/day × 30 days = $1500). Broken down by category.

- **NET PROFIT** — Gross profit − Allocated overhead, with net margin %. Green ring if positive, amber if negative.

💡 **If your "net profit" shows 100%**, you have zero
costs recorded — you'll see an amber warning telling you to record
expenses + overhead. Most rentals run at 30-50% real margin once
gas + payroll + overhead are honest.

💡 The P&L pulls revenue by **event_date** (not
created_at) — this matches the way the rest of the reports page
thinks about "when revenue happened" (the day you delivered),
which is also how your accountant will want to see it.

4. CSV export for accountant / QuickBooks

Below the P&L card on `/admin/reports` there's a green
"Accounting CSV export" box with three download buttons (scoped to
the same date range):

- **Booking expenses** — one row per per-booking expense (date, category label, amount, booking ID, customer, event date, driver hours, etc.)

- **Overhead** — one row per fixed monthly line active in the period (with group, category, monthly + annual amounts)

- **P&L summary** — single multi-line CSV (Revenue, each direct-cost category, Gross profit, each overhead category, NET PROFIT)

💡 Send the three files to your accountant at tax time, or import
into QuickBooks Online / Xero / a spreadsheet. Dates are ISO format
(YYYY-MM-DD) and amounts are plain decimals with no $ signs — universally
compatible.

⚙️ **Setup required (one time, in this order):**

- Run `supabase/accounting.sql` — creates
`booking_expenses` + `overhead_costs`
tables, RLS, and `default_driver_hourly_rate_cents`
setting

- Run `supabase/overhead_categories.sql` — creates
the dynamic `overhead_categories` table, drops the
fixed CHECK on `overhead_costs.category`, and seeds
~36 standard categories

- Run `supabase/booking_expense_categories.sql` —
creates the dynamic `booking_expense_categories`
table (with `supports_payroll_hours` flag for
labor-style categories), drops the fixed CHECK on
`booking_expenses.category`, and seeds 12 categories

Until you run all three, `/admin/overhead` and booking
detail pages will throw errors.$kbf$, $kbf$Operations$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();

insert into kb_articles (slug, title, body_md, category, tags, is_published) values
  ($kbf$help-tests$kbf$, $kbf$Testing checklist$kbf$, $kbf$Before going live, test these end-to-end:

- ☐ Public booking → Stripe test card `4242 4242 4242 4242` → check email + SMS arrive

- ☐ Create quote → send → approve as customer → pay

- ☐ Login to portal → see bookings → cancel one → confirm email goes out

- ☐ Refund a booking from admin → check Stripe + email

- ☐ Issue gift card (admin) → use in another booking → check balance decreases

- ☐ Buy gift card from `/gift-cards` (public) → recipient gets email → purchaser gets receipt → card appears in admin list

- ☐ Toggle "Public gift card sales" OFF on `/admin/gift-cards` → confirm `/gift-cards` shows "call us" message → toggle back ON

- ☐ As a referrer in /portal/referrals: request CREDIT payout → admin approves → recipient gets gift card email automatically

- ☐ As a referrer: request CASH payout → upload W9 → admin clicks "View W9 form" (opens private signed PDF) → approve → mark as paid with transfer ID

- ☐ Book a rental as a customer → sign the liability waiver (test card 4242...) → check signed record exists by querying `booking_waivers`

- ☐ Book a rental + check "My venue requires a COI" → fill venue info → admin sees it in `/admin/coi` → uploads PDF → customer gets email + sees download in portal

- ☐ As a customer with a paid booking 8+ hours out: click "Bad weather forecast?" → confirm → gift card code appears in email + booking shows cancelled

- ☐ Add a review in `/admin/reviews` → toggle Featured ON → check it appears in homepage carousel + on `/reviews` page

- ☐ Upload extra product photos in `/admin/products/[id]` → public `/items/[slug]` shows carousel + lightbox

- ☐ Enable unit tracking on Blowers → bulk-add 14 (BLW-01..BLW-14) → in dispatch, "Pick units" → confirm tags show in truck load

- ☐ Add a propane requirement to a generator product with "Per day" checked → book 3 days → checklist shows 3 tanks (not 1)

- ☐ In `/admin/fleet` edit a trailer → mark "electric dolly" as compatible → tag shows in the "Can carry" column

- ☐ Add VIN + tag on a vehicle → confirm columns render with uppercase monospace

- ☐ Add a CRUD inventory category → confirm it appears in the dropdown when creating an item

- ☐ Submit the public `/contact` form → check (1) row appears in `/admin/inbox`, (2) admin gets email at ADMIN_ALERT_EMAIL, (3) GHL contact created with general_inquiry tag

- ☐ Reply to a contact message from `/admin/inbox` → check customer receives the reply email, reply appears in the thread, and message is marked resolved

- ☐ With unresolved messages: dashboard shows amber "X unread messages in Contact Inbox" panel with top 5

- ☐ Run seed_starter_packages.sql → 8 packages appear in `/admin/packages` (all inactive)

- ☐ Edit a package → add 2-3 products from inventory → upload custom image via Upload button → toggle Active → confirm it appears at `/packages` public

- ☐ Change site font: `/admin/site` → SiteFontPicker → "Quicksand" → Save → public homepage refresh shows new font everywhere

- ☐ Self-hosted font: pick "Louis George Cafe (self-hosted)" → upload a .woff2 → Save → public site loads it via @font-face (check page source for the @font-face rule)

- ☐ (When configured) Send a test email to your inbound address → appears in /admin/inbox within ~30s with blue "Email" badge

- ☐ Create staff + driver users → login as each → verify role gating

- ☐ Driver marks stop delivered → captures proof photos + signature

- ☐ Record damage with protection vs without → check chargeable amounts

- ☐ Run `supabase/accounting.sql` → in `/admin/overhead` add a $1500/mo rent line (effective from today) → in any paid booking add a $40 gas expense + 3hr payroll → open `/admin/reports` → P&L card shows Revenue / Direct costs / Gross / Overhead / NET correctly$kbf$, $kbf$Setup$kbf$, array[$kbf$help$kbf$, $kbf$imported$kbf$], true)
on conflict (slug) do update set
  title = excluded.title,
  body_md = excluded.body_md,
  category = excluded.category,
  tags = excluded.tags,
  updated_at = now();
